#lang racket
(require "../sub.rkt" redex/reduction-semantics)

(test-judgment-holds (<: nat nat))
(test-judgment-holds (<: (Record [a nat] [b nat])
                         (Record [a nat] [b nat])))
(test-judgment-holds (<: (Record [a nat] [b nat] [c nat])
                         (Record [a nat] [b nat])))
(test-judgment-holds (<: (Record [a nat] [b nat] [c nat])
                         (Record [a nat] [c nat])))
(test-judgment-holds (<: (Record [a nat] [b nat] [c nat])
                         (Record [b nat] [c nat])))
(test-judgment-holds (<: (Record [b nat] [c (Record [a nat])])
                         (Record)))
(test-judgment-holds (<: (Record [a nat] [b (Record [a nat])] [c (Record)])
                         (Record [a nat] [b (Record)])))
(test-judgment-holds (<: (Record [a (Record [a nat])] [b (Record [a nat])] [c (Record [b nat])])
                         (Record [a (Record)]                              [c (Record)])))
(test-equal (judgment-holds (<: (Record [a nat] [b nat])
                                (Record [a nat] [b nat] [c nat])))
            #f)
(test-equal (judgment-holds (<: (Record)
                                nat))
            #f)
(test-equal (judgment-holds (<: nat
                                (Record)))
            #f)
